sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - echo 0
  #- npm i npminstall -g
install:
  - echo 0
  #- npminstall
script:
  - echo 0
  #- npm run ci
after_script:
  - echo 0
  #- npminstall codecov && codecov
